language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

env:
  - TYPO3_VERSION="^6.2.0"
  - TYPO3_VERSION="^7.6.0"
  global:
    secure: pj0LN2iXMab1i05K7MA7KRBhZ3zjVtDWLMPXm10wwCKWvA1jrn8ef9MwO/MuMgZc+ohQF89fkIHHjxJCOiitYwWgMd1o7Qt2QIcWEXmbE1qylHNo48LhBOSRzc24tWVEcPoay1HfR0kteTkJ64kW3f1Dn0bsoN4vqYXeFLrC9hY=

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  exclude:
    # TYPO3 6.2 only with PHP-Versions 5.4 - 5.6
    - php: 7.0
      env: TYPO3_VERSION="^6.2.0"
    - php: hhvm
      env: TYPO3_VERSION="^6.2.0"
    - php: nightly
      env: TYPO3_VERSION="^6.2.0"
    # TYPO3 7.6 only with PHP-Versions 5.5 - 7.0
    - php: 5.4
      env: TYPO3_VERSION="^7.6.0"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - breakpoint@schreibersebastian.de

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer --version
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
