<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_simple_faq"
 *
 * Auto generated by Extension Builder 2015-03-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple FAQ',
	'description' => 'A simple extension for frequently asked questions',
	'category' => 'plugin',
	'author' => 'Daniel Meyer',
	'author_email' => 'd.meyer@skyfillers.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);